routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});



Auth::routes();
//auth
Route::group(['middleware' => 'auth:admin', 'prefix' => 'admin', 'namespace' => 'Admin'],function(){  
Route::get('/', 'AdminController@index');
//Route::view('/admin', 'layouts.admin');
//blogs
Route::resource('blogs','BlogsController');
Route::post('blogs/data','BlogsController@data');
Route::post('blogs/upload','BlogsController@upload');
//categories
Route::resource('categories','CategoryController');
Route::post('/categories/data','CategoryController@data');
Route::post('/categories/upload','CategoryController@upload');
//authers
Route::resource('authers','AutherController');
Route::post('/authers/data','AutherController@data');
Route::post('/authers/upload','AutherController@upload');
 
});
    Route::get('/login/admin', 'Auth\LoginController@showAdminLoginForm');
    Route::get('/login/user', 'Auth\LoginController@showuserLoginForm');
    Route::get('/register/admin', 'Auth\RegisterController@showAdminRegisterForm');
    Route::get('/register/user', 'Auth\RegisterController@showuserRegisterForm');

    Route::post('/login/admin', 'Auth\LoginController@adminLogin');
    Route::post('/login/user', 'Auth\LoginController@userLogin');
    Route::post('/register/admin', 'Auth\RegisterController@createAdmin');
    Route::post('/register/user', 'Auth\RegisterController@createuser');

    //Route::view('/home', 'home')->middleware('auth');
    Route::get('home','HomeController@index')->middleware('auth');

    //home for users
    Route::get('/blogs', 'users\BlogsUserController@index')->name('user');
    Route::get('/blogs/{id}', 'users\BlogsUserController@show')->name('views');
   
   

resources/views/admin/auther.blade.php
@extends('admin.master')
@section('content')

<h1 class="text-center mb-4 mt-2">Authers</h1>
@if (session('message'))
<div class="alert alert-success alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>	
        <strong>{{ session('message') }}</strong>
</div>
@endif
<div class="row">
  <div class="col-3"><div class="row  d-flex justify-content-center">
     @include('admin.sidebar')
            </div>
  <div class="col-9">
  <div id="msg"></div>
<button name="add" type="buttn" class="btn btn-success btn-sm mb-5" id="add_data">ADD</button>
<table class="table table-bordered DataTable" style="width:100%" id="auther_table" >
<tr>
<thead>
<th>Auther name</th>
<th>Image</th>
<th>action</th>
</thead>
</tr>




</table>
</div>
</div>
</div>
<div id="autherModel" class="modal fade" role="dialog">
<div class="modal-dialog">
<div class="modal-content">
<form action="{{route('authers.store')}}" method="post" id="auther_form" enctype="multipart/form-data">

<div class="modal-header">

<button type="button" class="close" data-dismis="modal">&times;</button>
<h4 class="modal-title">Add Data</h4>

</div>
<div class="modal-body">@csrf

          <div class="alert alert-danger print-error-msg" style="display:none;"></div>
<div class="form-group ">
    <label>Auther Name</label>
    <input type="text" class="form-control"  aria-describedby="emailHelp" placeholder="Enterthe auther name" name="name" id="name">
    @error('name')
    <div class="mt-4 mb-4"><span class="alert alert-danger">{{$message}}</span></div>
    @enderror
    
  </div>
  <div class="form-group">
  <div class="custom-file">
    
    <input type="file" name="image" id="image" class="custom-file-input"> 
    <div id="image-holder" class="row mt-2 justify-content-center"> </div>
    @error('image')
    <div class="mt-4 mb-4"><span class="alert alert-danger">{{$message}}</span></div>
    @enderror
    <label class="custom-file-label">Image</label>
    </div>
  </div>
  


</div>
<div class="modal-footer">
<input type="hidden" name="auther_id" id="auther_id" value="">

<input type="hidden" name="button_action" id="button_action" value="insert">
<input type="submit" name="submit" id="action" value="add" class="btn btn-info">
<button type="button" class="close" data-dismis="modal">close</button>

</div>


</form>


</div>
</div>
@endsection
@section('scripts')

<script src="{{asset('public/js/auther.js')}}"></script>
@endsection

resources/views/admin/blog.blade.php
@extends('admin.master')
@section('content')

{{ csrf_field() }} 
<h1 class="text-center mb-4 mt-2">Blogs</h1>
@if (session('message'))
<div class="alert alert-success alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>	
        <strong>{{ session('message') }}</strong>
</div>
@endif
<div class="row">
  <div class="col-3"><div class="row  d-flex justify-content-center">
  @include('admin.sidebar')
  </div>
  <div class="col-9">
    <div id="msg"></div>
<button name="add" type="buttn" class="btn btn-success btn-sm mb-5" id="add_data">ADD</button>
<table  class="table table-bordered DataTable" style="width:100%" id="blog_table">

<tr>
<thead>
<th>Title</th>
<th>Description</th>
<th>image</th>
<th>order</th>
<th>active</th>
<th>views</th>
<th>Category Name</th>
<th>Auther Name</th>
<th>Actions</th>
</thead>
</tr>






</table>
</div>
</div>
</div>
<div id="dataModel" class="modal fade" role="dialog">
<div class="modal-dialog">
<div class="modal-content">
<form action="" method="post" id="data_form" enctype="multipart/form-data">

<div class="modal-header">

<button type="button" class="close" data-dismis="modal">&times;</button>
<h4 class="modal-title">Add Data</h4>


</div>
<div class="modal-body">@csrf
<div class="form-group ">
    <label>Title</label>
    <input type="text" class="form-control"  aria-describedby="emailHelp" placeholder="Enter the title" name="title" id="title">
    @error('title')
    <div class="mt-4 mb-4"><span class="alert alert-danger">{{$message}}</span></div>
    @enderror
    
  </div>
  <div class="form-group">
    <label>Description</label>
    <input type="text" class="form-control" aria-describedby="emailHelp" placeholder="Enter discription" name="description" id="description"> 
    @error('description')
    <div class="mt-4 mb-4"><span class="alert alert-danger">{{$message}}</span></div>
    @enderror
  </div>
  <div class="form-group">
  <div class="custom-file">
    <input type="file" name="image" id="image" class="custom-file-input"> 
    <div id="image-holder" class="row mt-2 justify-content-center"> </div>
    @error('image')
    <div class="mt-4 mb-4"><span class="alert alert-danger">{{$message}}</span></div>
    @enderror
    <label class="custom-file-label">Image</label>
    </div>
  </div>
  <div class="form-group">
    <label>Order</label>
    <input type="text" class="form-control" aria-describedby="emailHelp" placeholder="Enter order" name="order" id="order">
    @error('order')
    <div class="mt-4 mb-4"><span class="alert alert-danger">{{$message}}</span></div>
    @enderror 
  </div>
  <div class="form-group">
    <label for="exampleFormControlSelect1">Active</label>
    <select class="form-control" name="active" id="active">
      <option value="1">yes</option>
      <option value="0">no</option>
    </select>
  </div>
  <div class="form-group">
  <label for="exampleFormControlSelect1">Category</label>
    <select class="form-control"  name="cat_id" id="cat_id">
    @foreach($categories as $category)
    @if($category->parent_id != 0)
      <option value="{{$category->id}}">{{$category->name}}</option>
      @endif
      @endforeach
    </select>
    @error('cat_id')
    <div class="mt-4 mb-4"><span class="alert alert-danger">{{$message}}</span></div>
    @enderror
  </div>
  <div class="form-group">
  <label for="exampleFormControlSelect1">Auther</label>
    <select class="form-control"  name="auther_id" id="auther_id">
    @foreach($authers as $auther)
      <option value="{{$auther->id}}">{{$auther->name}}</option>
      @endforeach
    </select>
    @error('auther_id')
    <div class="mt-4 mb-4"><span class="alert alert-danger">{{$message}}</span></div>
    @enderror
  </div>

</div>
<div class="modal-footer">
<input type="hidden" name="blog_id" id="blog_id" value="">
<input type="hidden" name="button_action" id="button_action" value="insert">
<input type="submit" name="submit" id="action" value="add" class="btn btn-info">
<button type="button" class="close" data-dismis="modal">close</button>

</div>


</form>


</div>
</div>
@endsection
@section('scripts')

<script src="{{asset('public/js/blogs.js')}}"></script> 
@endsection

resources/views/admin/category.blade.php
@extends('admin.master')
@section('content')
{{ csrf_field() }} 
<h1 class="text-center mb-4 mt-2">Categories</h1>
@if (session('message'))
<div class="alert alert-success alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>	
        <strong>{{ session('message') }}</strong>
</div>
@endif

<input type="hidden" name="p_id" id="p_id" value="">
<div class="row">
  <div class="col-3 mb-5">
  <div class="row  d-flex justify-content-center">
  @include('admin.sidebar')
  </div>
  <div class="col-9">
    <div id="msg"></div>
  <button name="add" type="buttn" class="btn btn-success btn-sm mb-5" id="add_data">ADD</button>
<table  class="table table-bordered DataTable" style="width:100%"  id="cat_table">

<thead>
<th>Category Name</th>
<th>Icon</th>
<th>parent Category</th>
<th>actions</th>
</thead>
</tr>

<table class="table table-bordered DataTable"></table>



</table>
</div>
</div>
</div>
<div id="catModel" class="modal fade" role="dialog">
<div class="modal-dialog">
<div class="modal-content">
<form action="" method="post" id="cat_form">

<div class="modal-header">

<button type="button" class="close" data-dismis="modal">&times;</button>
<h4 class="modal-title">Add Data</h4>

</div>
<div class="modal-body">@csrf
<div class="form-group ">
    <label>Category Name</label>
    <input type="text" class="form-control"  aria-describedby="emailHelp" placeholder="Enter name" name="name" id="name">
    @error('name')
    <div class="mt-4 mb-4"><span class="alert alert-danger">{{$message}}</span></div>
    @enderror
    
  </div>
  <div class="form-group">
  <div class="custom-file">
    <input type="file" name="icon" id="icon" class="custom-file-input">
    <div id="image-holder" class="row mt-2 justify-content-center"> </div>
    @error('image')
    <div class="mt-4 mb-4"><span class="alert alert-danger">{{$message}}</span></div>
    @enderror
    <label class="custom-file-label">icon</label>
    </div>
  </div>
  <div class="form-group">
  <label for="exampleFormControlSelect1">Parent Category</label>
    <select class="form-control"  name="category" id="category">
    <option value="0"></option>
    @foreach($cats as $cat)
    @if($cat->parent_id==0)
      <option value="{{$cat->id}}">{{$cat->name}}</option>
      @endif
      @endforeach
    </select>
  </div>
  
  
<div class="modal-footer">
<input type="hidden" name="cat_id" id="cat_id" value="">
<input type="hidden" name="button_action" id="button_action" value="insert">
<input type="submit" name="submit" id="action" value="add" class="btn btn-info">
<button type="button" class="close" data-dismis="modal">close</button>

</div>


</form>


</div>
</div>
</div>
<div id="subCat" class="modal fade" role="dialog">
<div class="modal-dialog">
<div class="modal-content">
<form action="">
<ul>


<li> </li>

</ul>
</form>

</div>
</div>
@endsection
@section('scripts')
<script>
  var neWconfig = {
    parent_id: "{{ $id }}"
  }

</script>
<script src="{{asset('/public/js/category.js')}}"></script>
@endsection

resources/views/admin/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Categories</title>
    <link rel="stylesheet" type="text/css" href="{{asset('public/css/bootstrap.min.css')}}"/>  
    <link rel="stylesheet" href="{{asset('public/css/jquery.dataTables.css')}}">
    
  
    <style>
      .error{
        color:red;
        font-style:italic;
    }
  
  th{
    text-align:center;
  }
  
  </style>
   
</head>
<body>

<div class="container">
@yield('content')
</div>


<script src="{{asset('public/js/jquery-3.4.1.min.js')}}"></script>
<script src="{{asset('public/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('public/js/jquery.validate.min.js')}}"></script>
<script src="{{asset('public/js/additional-methods.min.js')}}"></script>
<script src="{{asset('public/js/bootstrap.min.js')}}"></script>
<script>
  var config = {
    url: "{{ url('/admin') }}",
    src:"{{asset('')}}"
  
  }

</script>


@yield('scripts')


</body>
</html>

resources/views/admin/sidebar.blade.php
<div class="col-12">
                <div class="card">
                    <div class="card-header">Dashboard</div>

                    <div class="card-body d-flex">
                       
                    <ul style="float:left;">
                    <li> Hi boss!</li>
                    <li><a href="{{route('authers.index')}}">Authers</a></li>
                    <li><a href="{{route('blogs.index')}}">Blogs</a></li>
                    <li><a href="{{route('categories.index')}}">Categories</a></li>
                    </ul>
                    </div>
                </div>
            </div>
        </div>

resources/views/admin/subcat.blade.php
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{{asset('css/bootstrap.min.css')}}"/>  
    <link rel="stylesheet" href="{{asset('css/jquery.dataTables.css')}}">
    
  

   
</head>
<body>

<div class="container">
<h1 class="text-center mb-4 mt-2">Categories</h1>
<button name="add" type="buttn" class="btn btn-success btn-sm mb-5" id="add_data">ADD</button>
<input type="hidden" name="p_id" id="p_id" value="">
<table id="cat_table" class="table table-bordered DataTable" style="width:100%">
<tr>
<th>Category Name</th>
<th>Icon</th>
<th>action</th>
</tr>
<tr>


</table>
</div>
<div id="catModel" class="modal fade" role="dialog">
<div class="modal-dialog">
<div class="modal-content">
<form action="" method="post" id="cat_form">

<div class="modal-header">

<button type="button" class="close" data-dismis="modal">&times;</button>
<h4 class="modal-title">Add Data</h4>

</div>
<div class="modal-body">@csrf
<div class="form-group ">
    <label>Category Name</label>
    <input type="text" class="form-control"  aria-describedby="emailHelp" placeholder="Enter name" name="name" id="name">
    
  </div>
  <div class="form-group">
    <label>Icon</label>
    <input type="text" class="form-control" aria-describedby="emailHelp" placeholder="Enter icon" name="icon" id="icon">
    
  </div>
  
  
<div class="modal-footer">
<input type="hidden" name="cat_id" id="cat_id" value="">
<input type="hidden" name="button_action" id="button_action" value="insert">
<input type="submit" name="submit" id="action" value="add" class="btn btn-info">
<button type="button" class="close" data-dismis="modal">close</button>

</div>


</form>


</div>
</div>
</div>
<div id="subCat" class="modal fade" role="dialog">
<div class="modal-dialog">
<div class="modal-content">
<form action="">
<ul>


<li> </li>

</ul>
</form>

</div>
</div>
</div>


















<script src="js/jquery-3.4.1.min.js"></script>
<script src="js/jquery.dataTables.min.js"></script>
<script src="js/bootstrap.min.js"></script>

<script> 
$(document).ready(function(){
$('#cat_table').DataTable({

"processing": true,
"serverSide": true,
"ajax":"{{route('cat_getdata')}}",
"columns":[

    {"data":"name"},
    {"data":"icon"},
    {"data":"parent_id"},
    {"data":"action", orderable:false,searchable:false}
    
]



});
$('#add_data').click(function(){

$('#catModel').modal('show');
$('#cat_form')[0].reset();
$('#form_output').html('');
$('#button_action').val('insert');

$('#action').val('add');

});
$('#cat_form').on('submit',function(event){

event.preventDefault();
var form_data=$(this).serialize();
$.ajax({


    url:"{{route('cat_postdata')}}",
    method:"POST",
    data:form_data,
    dataType:"json",
  
    
});

});
$(document).on('click','.edit',function(){
  var id = $(this).attr("id");
  $.ajax({
        url:"{{route('cat_actiondata')}}",
        method:'get',
        data:{id:id},
        dataType:'json',
        success:function(data){

          $('#name').val(data.name);
          $('#icon').val(data.icon);
          $('#parent_id').val(data.parent_id);
          $('#cat_id').val(id);
          $('#catModel').modal('show');
          $('#action').val('edit');
          $('.modal-title').text('Edit Data');
          $('#button_action').val('update');

        }


  })
});

  $(document).on('click','.delete',function(){
    var id = $(this).attr("id");
    if(confirm("are you sure you want to delete this?"))
   {
     $.ajax({
         url:"{{route('cat_removedata')}}",
         method:"get",
         data:{id:id},
         success:function(data){
           alert(data);
           $('#cat_table').DataTable().ajax.reload();
         }
     })
   }
   else{
     return false;
   }
  });

  $('.close').on('click',function(){
    $('#catModel').modal('hide');
  });

});
</script>

</body>
</html>